// js/stations.js
const stations = [
  // ---------- AM ----------
  { id: 'radio1',  name: 'Clarín CX2 AM580', emoji: '📻', url: 'https://radioclarin-zikoxweb.radioca.st/stream' },
  { id: 'radio2',  name: 'Rural CX4 AM610', emoji: '📻', url: 'https://radiolatina.live/9206/stream' },
  { id: 'radio3',  name: 'Sodre Clásica AM650', emoji: '📻', url: 'https://radios.iwstreaming.uy/8032/stream' },
  { id: 'radio4',  name: 'Sarandí CX6 AM690', emoji: '📻', url: 'https://radiolatina.live:10977/sarandi' },
  { id: 'radio5',  name: 'Oriental CX12 AM770', emoji: '📻', url: 'http://radiolatina.live:7906/1' },
  { id: 'radio6',  name: 'El Espectador CX14 AM810', emoji: '📻', url: 'https://espectador-1.nty.uy' },
  { id: 'radio7',  name: 'Carve CX16 AM850', emoji: '📻', url: 'https://streamingcasazorrilla.innovanexo.com:8000/radiocarve850.mp3' },
  { id: 'radio8',  name: 'Sport CX18 AM890', emoji: '📻', url: 'https://alba-uy-sport890-sport890.stream.mediatiquestream.com/index.m3u8' },
  { id: 'radio9',  name: 'Montecarlo CX20 AM930', emoji: '📻', url: 'https://streamingcasazorrilla.innovanexo.com:8000/montecarlo.mp3' },
  { id: 'radio10', name: 'Universal CX22 AM970', emoji: '📻', url: 'https://970universal-3.nty.uy/' },
  { id: 'radio11', name: 'Carve Deportiva CX24 AM1010', emoji: '📻', url: 'https://icecast13.innovanexo.com:9000/carvedeportiva.mp3' },
  { id: 'radio12', name: 'Uruguay CX26 AM1050', emoji: '📻', url: 'https://radios.iwstreaming.uy/8036/stream' },
  { id: 'radio13', name: 'Nacional CX30 AM1130', emoji: '📻', url: 'https://stream.rcast.net/73479' },
  { id: 'radio14', name: 'Radiomundo CX32 AM1170', emoji: '📻', url: 'http://ep1.enperspectiva.net:8000/radio.mp4' },
  { id: 'radio15', name: 'Centenario CX36 AM1250', emoji: '📻', url: 'https://rfm.radio.netgate.com.uy:8443/centenario' },
  { id: 'radio16', name: 'Fenix CX40 AM1330', emoji: '📻', url: 'https://sp3.servidorrprivado.com/8070/' },
  { id: 'radio17', name: 'La R AM1410', emoji: '📻', url: 'https://stream5.305stream.com/6162/' },
  { id: 'radio18', name: 'America CX46 AM1450', emoji: '📻', url: 'https://america-2.nty.uy/stream' },
  { id: 'radio19', name: 'Difusora Rochense', emoji: '📻', url: 'https://rochense-1.nty.uy/' },
  { id: 'radio20', name: 'FORTALEZA AM1320 Rocha', emoji: '📻', url: 'http://server-uk1.radioseninternet.net:9304/' },
  { id: 'radio21', name: 'NUEVA RADIO LASCANO AM1590', emoji: '📻', url: 'https://medios.ciudaddigital.com.uy:18050/NuevaRadio' },
  { id: 'radio22', name: 'Universo', emoji: '📻', url: 'https://streamingraddios.online/proxy/universoam?mp=/stream' },
  { id: 'radio23', name: 'La Voz de Melo', emoji: '📻', url: 'http://stream.zeno.fm/fzc86k96yy8uv' },
  { id: 'radio24', name: 'DIFUSORA TREINTA Y TRES AM1390', emoji: '📻', url: 'https://server-usa2.radioseninternet.net/8132/stream' },
  { id: 'radio25', name: 'COLONIA AM550', emoji: '📻', url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/COLONIA_ADP.aac' },
  { id: 'radio26', name: 'Acuarela Melo AM1520', emoji: '📻', url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/COLONIA_ADP.aac' },
  { id: 'radio27', name: 'Cristal Las Piedras AM1470', emoji: '📻', url: 'http://usa15.ciudaddigital.com.uy:8126/CristalAM' },
  { id: 'radio28', name: 'ARAPEY Artigas AM1450', emoji: '📻', url: 'http://emisiones.com.uy:8085/arapey' },
  { id: 'radio29', name: 'TACUAREMBO AM1280', emoji: '📻', url: 'http://usa15.ciudaddigital.com.uy:8114/TacuaremboAM' },
  { id: 'radio30', name: 'DIFUSORA SORIANO AM1210', emoji: '📻', url: 'http://usa15.ciudaddigital.com.uy:8094/DifusoraSoriano' },
  { id: 'radio31', name: 'RADIO DURAZNO AM1430', emoji: '📻', url: 'http://usa15.ciudaddigital.com.uy:8038/DuraznoAM' },
  { id: 'radio32', name: 'EL LIBERTADOR AM1210', emoji: '📻', url: 'http://s4.viastreaming.net:7200/stream.mp3' },
  { id: 'radio33', name: 'RADIO ZORRILLA AM1400 Tacuarembó', emoji: '📻', url: 'http://server-uk1.radioseninternet.net:9312/' },
  { id: 'radio34', name: 'RADIO PAYSANDU AM1240', emoji: '📻', url: 'https://streamingv2.shoutcast.com/radio-paysandu-cw35' },
  { id: 'radio35', name: 'RBC PIRIAPOLIS AM1210', emoji: '📻', url: 'http://usa15.ciudaddigital.com.uy:8058/RbcAM' },
  { id: 'radio36', name: 'Continental', emoji: '📻', url: 'https://edge02.radiohdvivo.com/stream/continental' },
  { id: 'radio37', name: 'Radio 10', emoji: '📻', url: 'https://radio10.stweb.tv/radio10/live/playlist.m3u8' },
  { id: 'radio38', name: 'Mitre', emoji: '📻', url: 'https://24443.live.streamtheworld.com/AM790_56.mp3' },
  { id: 'radio39', name: 'Nacional (Argentina)', emoji: '📻', url: 'http://sa.mp3.icecast.magma.edge-access.net:7200/sc_rad1' },
  { id: 'radio40', name: 'Del Plata', emoji: '📻', url: 'http://181.119.157.98:8800/amdelplata.mp3' },
  { id: 'radio41', name: 'Splendid', emoji: '📻', url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/AM990AAC.aac' },

  // ---------- FM ----------
  { id: 'radio42', name: 'CHUI 87.9 FM', emoji: '🎵', url: 'https://stm11.xcast.com.br:11288/stream' },
  { id: 'radio43', name: 'CADENA DE LA COSTA FM88.3 La Paloma', emoji: '🎵', url: 'https://s3.netradiofm.com/p/6112/stream' },
  { id: 'radio44', name: 'Atlántica FM89.3', emoji: '🎵', url: 'https://atlanticafm.radioca.st/stream' },
  { id: 'radio45', name: 'ACUARIO FM94.9', emoji: '🎵', url: 'https://radio25-zikoxstream.radioca.st/stream' },
  { id: 'radio46', name: 'CONQUISTADOR FM97.3 Treinta y Tres', emoji: '🎵', url: 'http://198.204.234.10:8143/index.html' }, // Puede ser stream, pero dejamos
  { id: 'radio47', name: 'FM La Paloma 102.1', emoji: '🎵', url: 'https://stream.radioinfo.ar/p/6112/' },
  { id: 'radio48', name: 'FM Coronilla 102.3', emoji: '🎵', url: 'https://streaming01.shockmedia.com.ar/9184/stream' },
  { id: 'radio49', name: 'ESTEÑA FM103.1 Castillos', emoji: '🎵', url: 'https://stream.radiopro.uy/listen/estena/estena' },
  { id: 'radio50', name: 'VIDA FM104.7 La Paloma', emoji: '🎵', url: 'http://usa15.ciudaddigital.com.uy:8048/VidaFM' },
  { id: 'radio51', name: 'NUEVA ONDA FM105.3 CHUY', emoji: '🎵', url: 'https://stream-176.zeno.fm/mz1dytxe2wzuv' },
  { id: 'radio52', name: 'ONDA MARINA FM106.3 La Paloma', emoji: '🎵', url: 'https://marina-2.nty.uy/' },
  { id: 'radio53', name: 'AMERICA FM107.5 Sta Vitoria', emoji: '🎵', url: 'http://stm1.aovivodigital.com.br:10676/test.aac' },
  { id: 'radio54', name: 'LA COSTA FM88.3', emoji: '🎵', url: 'https://streaming3.hostingmontevideo.com:8074/stream' },
  { id: 'radio55', name: 'DEL MOLINO FM89.3', emoji: '🎵', url: 'http://149.202.198.86:8915/' },
  { id: 'radio56', name: 'ACTIVA RIVERA FM89.9', emoji: '🎵', url: 'https://radios.iwstreaming.uy/8010/stream' },
  { id: 'radio57', name: 'RADIO CINCO FM89.7 TRINIDAD', emoji: '🎵', url: 'http://emisiones.com.uy:8084/cinco.mp3' },
  { id: 'radio58', name: 'OLDIES FM90.3', emoji: '🎵', url: 'http://51.15.152.81:8085/' },
  { id: 'radio59', name: 'FUTURA FM91.1', emoji: '🎵', url: 'http://radios-uy.cdn.nedmedia.io/radios/uy/futura.m3u8' },
  { id: 'radio60', name: 'URBANA FM92.5', emoji: '🎵', url: 'http://streamingsc.urbana.com.uy:8000/' },
  { id: 'radio61', name: 'INOLVIDABLE FM93.1', emoji: '🎵', url: 'http://stream.zenolive.com/6m1ba7yt3vduv' },
  { id: 'radio62', name: 'CONCIERTO FM95.1', emoji: '🎵', url: 'http://195.154.56.114:7026/listen.pls' },
  { id: 'radio63', name: 'TREINTA Y TRES FM94.3', emoji: '🎵', url: 'http://server-uk1.radioseninternetuy.com:8138/listen.pls?sid=1' },
  { id: 'radio64', name: 'CITY FM95.1 DURAZNO', emoji: '🎵', url: 'http://usa15.ciudaddigital.com.uy:8030/CityFM' },
  { id: 'radio65', name: 'DEL PLATA FM95.5', emoji: '🎵', url: 'http://radios-mp3-uy.cdn.nedmedia.io/uy-delplata.mp3' },
  { id: 'radio66', name: 'ALFA FM96.3', emoji: '🎵', url: 'http://radioonline.netgate.com.uy:8000/alfafm' },
  { id: 'radio67', name: 'VISION FM96.5 FRAY BENTOS', emoji: '🎵', url: 'http://emisiones.com.uy:8108/vision' },
  { id: 'radio68', name: 'BABEL FM97.1', emoji: '🎵', url: 'http://radiosrnu.com:9340/stream' },
  { id: 'radio69', name: 'DIAMANTE FM98.7', emoji: '🎵', url: 'http://qwcast.com:9870/diamante' },
  { id: 'radio70', name: 'FEDERAL FM99.1', emoji: '🎵', url: 'http://usa15.ciudaddigital.com.uy/medios/FederalFM/audio/directo.pls' },
  { id: 'radio71', name: 'DEL SOL FM99.5', emoji: '🎵', url: 'http://radio.dl.uy:9950/radio' },
  { id: 'radio72', name: 'DIGITAL FM100.1', emoji: '🎵', url: 'http://96.127.183.74:8510/listen.pls' },
  { id: 'radio73', name: 'AIRE FM100.3', emoji: '🎵', url: 'http://195.154.182.222:27125/stream' },
  { id: 'radio74', name: 'EXTREMO FM100.9 SALTO', emoji: '🎵', url: 'http://192.240.99.146:8111/bour' },
  { id: 'radio75', name: 'ASPEN FM103.5', emoji: '🎵', url: 'http://67.222.24.62:9300/' },
  { id: 'radio76', name: 'LATINA FM103.7', emoji: '🎵', url: 'http://www.emisorasuruguayas.com/latina-1037-fm' }, // Puede no ser directo, pero dejamos
  { id: 'radio77', name: 'FM Hit', emoji: '🎵', url: 'https://hit-1.nty.uy/stream' },
  { id: 'radio78', name: 'METROPOLIS FM', emoji: '🎵', url: 'https://metropolis-web-2.nty.uy/' },
  { id: 'radio79', name: 'Azul FM101.9', emoji: '🎵', url: 'https://azul-3.nty.uy/' },
  { id: 'radio80', name: 'OCEANO FM93.9', emoji: '🎵', url: 'https://oceano-2.nty.uy/netradio/listen.mp3' },
  { id: 'radio81', name: 'RADIOCERO FM104.3', emoji: '🎵', url: 'https://radiolatina.live:10966/stream' },
  { id: 'radio82', name: 'GALAXIA FM105.9', emoji: '🎵', url: 'http://node-31.zeno.fm/bf4gt1pem0quv' },
  { id: 'radio83', name: 'Bajo La Lupa', emoji: '🎵', url: 'https://cast1.asurahosting.com/proxy/bajolalu/stream' },
  { id: 'radio84', name: 'Némesis Radio', emoji: '🎵', url: 'https://c21.radioboss.fm/stream/171' },

  // ---------- Internacionales ----------
  { id: 'radio85', name: 'CBN Florianópolis', emoji: '🌎', url: 'https://20843.live.streamtheworld.com/CBN_FLO.mp3' },
  { id: 'radio86', name: 'Gaucha POA', emoji: '🌎', url: 'https://1132747t.ha.azioncdn.net/primary/gaucha_rbs.sdp/playlist.m3u8' },
  { id: 'radio87', name: 'Guaiba POA', emoji: '🌎', url: 'https://radio.saopaulo01.com.br:10827/stream' },
  { id: 'radio88', name: 'Pampa POA', emoji: '🌎', url: 'http://cast4.audiostream.com.br:8653/mp3' },
  { id: 'radio89', name: 'Jovem Pan Florianópolis', emoji: '🌎', url: 'http://wz5.dnip.com.br/jfloripa/jfloripa.stream/playlist.m3u8' },
  { id: 'radio90', name: 'EXTERIOR ESPAÑA', emoji: '🌎', url: 'https://rtvelivestream.akamaized.net/rtvesec/rne/rne_re_main.m3u8' },
  { id: 'radio91', name: 'RADIO FRANCIA INTERNACIONAL', emoji: '🌎', url: 'https://rfienespagnol64k.ice.infomaniak.ch/rfienespagnol-64.mp3' }
];